### ISSUE TITLE
Questions: Transaction

### ISSUE THREAD

**Issue by mattherick** [dkd/paymill-ruby#1]
How can I create transactions to paymill?

**Comment by flippingbits** [comment]
Hi,

creating transactions is pretty simple.
First, make sure that you're authenticated:

```
require "paymill"
Paymill.api_key = "your-api-key"
```

Then you can create the `Transaction` object:

```
Paymill::Transaction.create(amount:      1999,
                            currency:    "EUR",
                            description: "Foo.",
                            token:       "_foo")
```

The call to `Paymill::Transaction.create` will return a fresh object that contains the transaction's paymill id.

**Comment by mattherick** [comment]
Thanks for the quick reply! 
I have another question: why you should create a Paymill::Client?

**Comment by flippingbits** [comment]
You should have a look at the official API documentation:
https://www.paymill.de/documentation/referenz/api-referenz/index.html#document-clients
