### ISSUE TITLE
Subscriptions trail_start & trail_end are not accessible

### ISSUE THREAD

**Issue by LosVogas** [dkd/paymill-ruby#10]
Hey, 
is there any smart reason why attributes like "trail_start" or "trail_end" shouldn't be accessible for subscriptions?

in subscriptions.rb these attributes are not marked as accessible.
Since I always have to check with paymill if client is still entitled to use my product/service on login, would be nice if I could use these fields.

am I wrong?
thanks for your help

**Comment by flippingbits** [comment]
No, I guess they were introduced in version 2 of the Paymill API.

I'll add them.

**Comment by LosVogas** [comment]
Thanks! Awesome. :-)
