### ISSUE TITLE
It isn't possible to pass in filters to "listview" methods

### ISSUE THREAD

**Issue by airblade** [dkd/paymill-ruby#11]
For example the [API call to list all transactions](https://www.paymill.com/en-gb/documentation-3/reference/api-reference/index.html#list-transactions) takes an `offset`.

However this gem doesn't support that.

**Comment by flippingbits** [comment]
I'm happy to merge a PR.
Otherwise I'll work on this if I find some time :)

**Comment by flippingbits** [comment]
Merged :)

**Comment by airblade** [comment]
Thanks everyone!
