### ISSUE TITLE
undefined method `update_attributes' for Paymill::Client

### ISSUE THREAD

**Issue by previousgtbash** [dkd/paymill-ruby#13]
Hi everybody, I have a problem using the update operations on a Paymill Client. I use the same sample code given in the repo:

``` ruby
client = Paymill::Client.find(valid_client_id)
client.update_attributes(email: "Lets try it")

NoMethodError: undefined method `update_attributes' for #<Paymill::Client:0x007fb9dc75a8f8>

```

I investigate a little bit and it seems that the Paymill::Client class does not include the Paymill::Operation::Update module, or at least thats what the ruby console says.

``` ruby
Paymill::Client.included_modules
=> [Paymill::Operations::Find,
 Paymill::Operations::Delete,
 Paymill::Operations::Create,
 Paymill::Operations::All,
 Metaclass::ObjectMethods,
 Mocha::ObjectMethods,
 PP::ObjectMixin,
 FriendlyId::ObjectUtils,
 JSON::Ext::Generator::GeneratorMethods::Object,
 ActiveSupport::Dependencies::Loadable,
 Kernel]
```

Am I doing something wrong?

**Comment by flippingbits** [comment]
The `update_attributes` method was not released yet but is available in this Git repository.

I just released a new version.
