### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by flippingbits** [dkd/paymill-ruby#16]
I think this gem needs some documentation :)

**Comment by esbanarango** [comment]
+1

**Comment by flippingbits** [comment]
I've added some documentation.
It should be available at http://rubydoc.info/gems/paymill/frames/index soon.

**Comment by ryanharkins** [comment]
I had changed a bit the README file and added some more documentation but sent the pull request to Paymill's fork (https://github.com/Paymill/paymill-ruby/pull/1). If you think it's any good I could close the old pull request and send another here.

**Comment by flippingbits** [comment]
go for it :)
