### ISSUE TITLE
Testing the API

### ISSUE THREAD

**Issue by zamith** [dkd/paymill-ruby#31]
Hi guys,

I've been looking at the tests and one thing strikes me as not being awesome, the tests are not validated against the real API.

By using WebMock, this wrapper may be completely outdated and the test will still be green, which I believe is a problem.

My proposal to solve this is twofold, and I would like to know your opinion before giving this any more thought.

First, I would build a fake server to mimic paymill's, this would allow us to get rid of webmock all together and just run the actual requests against this server. This is also nice for someone that wants to do integration testing on an app using this gem, so it's a win win situation.

This, however, does not solve the problem of green tests when in fact it's outdated. With a fake server set up, this problem could be solved by running the test locally against the fake server, so it is fast, but on the CI running it against a paymill's sandbox.

So, locally the tests would be fast, if the API changes in a way that is not supported by the gem, the tests on the CI fail and we can update the gem and the fake server (hopefully such drastic changes to the API won't happen often).

What do you think?

**Comment by flippingbits** [comment]
Hey zamith,

I think this is a good idea.
I would appreciate a PR.

Cheers

**Comment by zamith** [comment]
@flippingbits I envisioned this more as a separate gem than a part of this one, would that be ok with you? I would definitely need your collaboration, though.

**Comment by flippingbits** [comment]
What are the arguments for creating a separate gem?
Will the fake server be needed in any other places?

**Comment by zamith** [comment]
Exactly. As I said in the first post, someone using the API can use this fake server to do integration tests against.

A good example is https://github.com/thoughtbot/fake_braintree.

**Comment by flippingbits** [comment]
Sounds good. Do you want to start it on your own and ping me if you need any help or should I start the project?

**Comment by zamith** [comment]
It's the same by me. I won't be able to start coding until tomorrow, if you want to get going, you can start it. I'll help either way.

**Comment by zamith** [comment]
@flippingbits Just create the repo and added you as a collab, I'll probably work on it later today.

https://github.com/zamith/fake-paymill

**Comment by flippingbits** [comment]
Thanks! :) :+1:

**Comment by Nerian** [comment]
How is the progress on this? it would be very valuable if this project could be completed.

This could serve as a template: https://github.com/thoughtbot/fake_braintree

**Comment by flippingbits** [comment]
You might ask @zamith

**Comment by jorge-d** [comment]
+1, This would be awesome !

**Comment by zamith** [comment]
I'll get around to it as soon as I can. I don't want to provide a deadline that I can't keep, so I won't.

If anyone wants to help out on this, it would be great.

**Comment by flippingbits** [comment]
I close this ticket for now and suggest that you head over to https://github.com/zamith/fake-paymill.

**Comment by zamith** [comment]
Hey everyone, sorry for such a delay, but finally got around to it.

It's still at a very early stage (it just supports `Paymill::Client.all` for now), but the wiring is mostly done.

Check it out at [zamith/fake-paymill](https://github.com/zamith/fake-paymill).

There's a sample app at [zamith/fake_paymill_dummy_app](https://github.com/zamith/fake_paymill_dummy_app).
