### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by zamith** [dkd/paymill-ruby#40]
What do you think of adding some kind of logging when a request is made? At least for what goes out and what comes in.

Braintree does this: https://github.com/braintree/braintree_ruby/blob/1e989120565d3e568ff577d4b02083f4b4be2301/lib/braintree/http.rb#L65-L75

**Comment by flippingbits** [comment]
Looks good and helpful to me!

**Comment by zamith** [comment]
Added in #42

**Comment by flippingbits** [comment]
So I close this for now since it's added in #42.

**Comment by zamith** [comment]
@flippingbits Sure. Thought it was already closed.
