### ISSUE TITLE
The development mode doesn't seem to work.

### ISSUE THREAD

**Issue by bencolon** [dkd/paymill-ruby#43]
Hi guys,

If I try to turn `Paymill.development` to `true`, I get a first 400 error because the port is still set to 443. (request : http://api.paymill.com:443/v2/payments/)

So, I add `Paymill.api_port = 80` to force the port but I get another error :

```
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Any ideas ?

**Comment by zamith** [comment]
@bencolon The development mode is not to be used against paymill, but it is internally by [fake-paymill](https://github.com/zamith/fake-paymill).

I have proposed to take it out of README. Sorry for the confusion.

**Comment by bencolon** [comment]
Crystal clear. Thanks for answering me.
