### ISSUE TITLE
Dealing with multiple API keys

### ISSUE THREAD

**Issue by akshayrawat** [dkd/paymill-ruby#5]
Currently the API key is set as a class level variable. I'm working on an application which has multiple paymill api keys. To handle this scenario, the public methods should optionally accept an api key as an argument.

Let me know if you have any ideas around this.

**Comment by flippingbits** [comment]
Hi,
you might just change the API key before starting a new request, e.g.:

```
Paymill.api_key = "first_key"
Paymill::Client.create(...)
Paymill.api_key = "second_key"
Paymill::Client.create(...)
```
