### ISSUE TITLE
Are there plans to adapt to v2.1 of the API?

### ISSUE THREAD

**Issue by semiomant** [dkd/paymill-ruby#50]
for example:

```
[main](0)--2014-09-12 13:39:04 +0200 >>Paymill::Subscription.update_attributes "sub_1cd06dcccbabb8272cc3", offer: "offer_0a5bd16a30f0db6fa567", offer_change_type: 0
```

Paymill::APIError: offer_change_type
from /Users/chusek/.rvm/gems/ruby-1.9.3-p392@droidmanager/gems/paymill-0.4.0/lib/paymill/request/validator.rb:27:in `validate_response_data'

**Comment by flippingbits** [comment]
Not yet. I'd be happy to merge a PR :)

**Comment by semiomant** [comment]
Thanks for the answer.
I wrangled with the gem code for half a day, but in the end I was easier to build a lib class on top of rest-client gem, which can do any paymill call with a little meta-programming.
