### ISSUE TITLE
INFO: gem 'paymill', '~> 0.4.0' 

### ISSUE THREAD

**Issue by lgs** [dkd/paymill-ruby#51]
paymill gem 0.4.0 is dated September 2, 2013 (15.5 KB) on [rubygems.org](https://rubygems.org/gems/paymill), while master branch is update recently:  

`latest commit ea32f1e4a8 Stefan Sprenger flippingbits authored on 29 Jul` 

is that correct or did you miss a gem bumping ?

**Comment by flippingbits** [comment]
I'll release a new version soon.

**Comment by mszyndel** [comment]
How is new version coming along? I heard it's gonna be available in August couple months ago and it's end of October now...

**Comment by flippingbits** [comment]
There you go: http://rubygems.org/gems/paymill

I've released version 0.5 today.
