### ISSUE TITLE
Hostname was not match with the server certificate

### ISSUE THREAD

**Issue by dkrusenstrahle** [dkd/paymill-ruby#9]
Hello,

I am trying to use you gem in my Ruby on Rails 3.2.9 application.
It works perfectly fine on my local Mac but on Heroku I get this error:

OpenSSL::SSL::SSLError (hostname was not match with the server certificate)

Is there something I need to do on Heroku or in code?

Thankful for all help!

**Comment by abarre** [comment]
Look at #6.

I experience a problem with ruby 1.8.7.
What is the ruby version in Heroku?

**Comment by dkrusenstrahle** [comment]
From what I can see, Heroku uses: ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]
Have you gotten it to work with Heroku?

**Comment by mariuszlusiak** [comment]
I had the same issue with current default Ruby on Heroku (1.9.2), but changing the Ruby version to 1.9.3 resolved the problems.

**Comment by dkrusenstrahle** [comment]
I added ruby "1.9.3" to my gem file and pushed to Heroku again and it works now. Thanks!

**Comment by flippingbits** [comment]
That's a weird issue. I'll have a look at it ASAP.

**Comment by flippingbits** [comment]
FYI: I haven't found anything but I can confirm this issue :/

**Comment by dongennl** [comment]
Many of these 'hostname' errors seem related to OS X and OpenSSL

this fixed it for me on OS X 7.5:

rvm pkg install openssl
rvm remove 1.9.3
rvm install 1.9.3 --with-openssl-dir=$rvm_path/usr --with-gcc=clang

**Comment by flippingbits** [comment]
Can you please check again if ad4e165567fb7a7a48ba6c89ff5e5f3ca62d5373 fixes your problems? It works for me.

**Comment by flippingbits** [comment]
Please reopen the issue if you're still facing problems.
